apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  volumes:
    - name: my-volumen-env
      configMap:
        name: my-env
  containers:
  - command:
    - sleep
    - "3600"
    image: vtuson/busybox
    name: busybox
    volumeMounts:
      - mountPath: /env
        name: my-volumen-env
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
