apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox-secret
spec:
  volumes:
    - name: my-volumen-secret
      secret:
        secretName: my-secret
  containers:
  - command:
    - sleep
    - "3600"
    image: vtuson/busybox
    name: busybox
    volumeMounts:
      - mountPath: /secrets
        name: my-volumen-secret
        readOnly: true
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}